UserBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: UserBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: 255
            nullable: true
        name:
            type: string
            length: 255
            nullable: true
        email:
            type: string
            length: 255
            nullable: true
        password:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }
